export const candidateTags = [
  { label: "Array", value: "Array" },
  { label: "String", value: "String" },
  { label: "Math", value: "Math" },
  { label: "Tree", value: "Tree" },
  { label: "Graph", value: "Graph" },
  { label: "Dynamic Programming", value: "Dynamic Programming" },
  { label: "Backtracking", value: "Backtracking" },
  { label: "Design", value: "Design" },
  { label: "Bit Manipulation", value: "Bit Manipulation" },
  { label: "Greedy", value: "Greedy" },
  { label: "Depth-first Search", value: "Depth-first Search" },
  { label: "Breadth-first Search", value: "Breadth-first Search" },
  { label: "Binary Search", value: "Binary Search" },
  { label: "Two Pointers", value: "Two Pointers" },
  { label: "Sort", value: "Sort" },
  { label: "Heap", value: "Heap" },
  { label: "Hash Table", value: "Hash Table" },
  { label: "Stack", value: "Stack" },
  { label: "Queue", value: "Queue" },
  { label: "Linked List", value: "Linked List" },
  { label: "Union Find", value: "Union Find" },
  { label: "Trie", value: "Trie" },
  { label: "Binary Indexed Tree", value: "Binary Indexed Tree" },
  { label: "Segment Tree", value: "Segment Tree" },
  { label: "Binary Search Tree", value: "Binary Search Tree" },
  { label: "Recursion", value: "Recursion" },
  { label: "Divide and Conquer", value: "Divide and Conquer" },
  { label: "Sliding Window", value: "Sliding Window" },
  { label: "Topological Sort", value: "Topological Sort" },
  { label: "Random", value: "Random" },
  { label: "Geometry", value: "Geometry" },
  { label: "Map", value: "Map" },
  { label: "Set", value: "Set" },
];
